const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const PokemonSchema = new Schema({
  id: { type: Number, required: true, unique: true },
  name: { type: String, required: true },
  generation: { type: Number, required: true },
  pokemon_type: { type: [String], required: true },
  RBYFRLG: { type: Number, required: false },
  LGPE: { type: Number, required: false },
  GSC: { type: Number, required: false },
  HGSS: { type: Number, required: false },
  RSE: { type: Number, required: false },
  ORAS: { type: Number, required: false },
  DPBDSP: { type: Number, required: false },
  Pt: { type: Number, required: false },
  BW: { type: Number, required: false },
  B2W2: { type: Number, required: false },
  XY_Central: { type: Number, required: false },
  XY_Coastal: { type: Number, required: false },
  XY_Mount: { type: Number, required: false },
  SM_Alola: { type: Number, required: false },
  SM_Melemele: { type: Number, required: false },
  SM_Akala: { type: Number, required: false },
  SM_Ulaula: { type: Number, required: false },
  SM_Poni: { type: Number, required: false },
  USUM_Alola: { type: Number, required: false },
  USUM_Melemele: { type: Number, required: false },
  USUM_Akala: { type: Number, required: false },
  USUM_Ulaula: { type: Number, required: false },
  USUM_Poni: { type: Number, required: false },
  SwSh_Galar: { type: Number, required: false },
  SwSh_Isle: { type: Number, required: false },
  SwSh_Crown: { type: Number, required: false },
  LA: { type: Number, required: false },
  SV_Paldea: { type: Number, required: false },
  SV_Kitakami: { type: Number, required: false },
  SV_Blueberry: { type: Number, required: false },
  hp: { type: Number, required: true },
  attack: { type: Number, required: true },
  defense: { type: Number, required: true },
  special_attack: { type: Number, required: true },
  special_defense: { type: Number, required: true },
  speed: { type: Number, required: true },
  total: { type: Number, required: true },
  type1: { type: String, required: true },
  type2: { type: String, required: false },
  ability1: { type: String, required: true },
  ability2: { type: String, required: false },
  hidden_ability: { type: String, required: false },
  height: { type: Number, required: true },
  weight: { type: Number, required: true },
  HP_EVs: { type: Number, required: false },
  Attack_EVs: { type: Number, required: false },
  Defense_EVs: { type: Number, required: false },
  Special_Attack_EVs: { type: Number, required: false },
  Special_Defense_EVs: { type: Number, required: false },
  Speed_EVs: { type: Number, required: false },
  experience_value: { type: Number, required: true },
  catch_rate: { type: Number, required: true },
  experience_growth: { type: String, required: true },
  base_friendship: { type: Number, required: true },
  pokedex_color: { type: String, required: true },
  gender_ratio: { type: String, required: true },
  egg_cycles: { type: Number, required: true },
  egg_group1: { type: String, required: true },
  egg_group2: { type: String, required: false },
  evolution_method: { type: String, required: false },
});

module.exports = mongoose.model("pokemons", PokemonSchema);
